<?xml version="1.0" ?>
<robot name="lab_wood_table" xmlns:xacro="http://ros.org/wiki/xacro">

<!-- Property List -->
<xacro:property name="pi" value="3.1415926535897931" />
<xacro:property name="table_base_length" value="0.9144" />
<xacro:property name="table_thickness" value="0.0508" />
<xacro:property name="table_base_width" value="0.4572" />

<xacro:property name="leg_height" value="0.4826" />
<xacro:property name="leg_length" value="0.06" />
<xacro:property name="leg_width" value="0.06" />


<!-- Color macros -->
<xacro:macro name="material_brown_transparent">
        <material name="brown_transparent">
                <color rgba="${139/255} ${69/255} ${19/255} 0.4" />
        </material>
</xacro:macro>


<!-- Base Link -->
<link name = "table_base">
<inertial>
 <origin xyz = "0 0 ${leg_height}" />
 <mass value = "1.0" />
 <inertia ixx="1" ixy="0"  ixz="0"
               iyy="1" iyz="0"
               izz="1" />
 </inertial>
<visual>
  <origin xyz = "0 0 ${leg_height}" />
  <geometry>
     <box size="${table_base_width} ${table_base_length} ${table_thickness}"/>
  </geometry>
  <material name="brown_transparent"/>
</visual>
<collision>
  <origin xyz = "0 0 ${leg_height}" />
  <geometry>
     <box size="${table_base_width} ${table_base_length} ${table_thickness}"/>
  </geometry>
  <material name="brown_transparent"/>
</collision>
</link>


<!--First Leg -->
<link name = "first_leg">
<inertial>
      <mass value="1.0" />
      <origin xyz="0 0 ${-leg_height}" />
      <inertia ixx="0.1" ixy="0"  ixz="0"
               iyy="0.1" iyz="0"
               izz="0.01" />
    </inertial> 
<visual>
  <origin xyz="0 0 ${-leg_height}" rpy="0 0 0" />
  <geometry>
        <box size="${leg_width} ${leg_width}  ${leg_height}"/>
  </geometry>
  <material name="brown_transparent"/>
</visual>
<collision>
  <origin xyz="0 0 ${-leg_height}" rpy="0 0 0" />
  <geometry>
        <box size="${leg_width} ${leg_width} ${leg_height}"/>
  </geometry>
  <material name="brown_transparent"/>
</collision>
</link>

<!-- Base to First Leg-->
<joint name="base_to_first_leg" type="fixed">
  <parent link="table_base"/>
  <child link="first_leg"/>
  <axis xyz="0 0 1"/>
  <origin rpy="0.0 0.0 0.0" xyz="${table_base_width/2-0.03} ${table_base_length/2-0.03} ${leg_height*1.5}"/>
</joint>

<!--Second Leg -->
<link name = "second_leg">
<inertial>
      <mass value="1.0" />
      <origin xyz="0 0 ${-leg_height}" />
      <inertia ixx="0.1" ixy="0"  ixz="0"
               iyy="0.1" iyz="0"
               izz="0.01" />
    </inertial> 
<visual>
  <origin xyz="0 0 ${-leg_height}" rpy="0 0 0" />
  <geometry>
        <box size="${leg_width} ${leg_width} ${leg_height}"/>
  </geometry>
  <material name="brown_transparent"/>
</visual>
<collision>
  <origin xyz="0 0 ${-leg_height}" rpy="0 0 0" />
  <geometry>
        <box size="${leg_width} ${leg_width} ${leg_height}"/>
  </geometry>
  <material name="brown_transparent"/>
</collision>
</link>

<!-- Base to Second Leg-->
<joint name="base_to_second_leg" type="fixed">
  <parent link="table_base"/>
  <child link="second_leg"/>
  <axis xyz="0 0 1"/>
  <origin rpy="0.0 0.0 0.0" xyz="-${table_base_width/2 - 0.03} -${table_base_length/2 - 0.03} ${leg_height*1.5}"/>
</joint>

<!--Third Leg -->
<link name = "third_leg">
<inertial>
      <mass value="1.0" />
      <origin xyz="0 0 ${-leg_height}" />
      <inertia ixx="0.1" ixy="0"  ixz="0"
               iyy="0.1" iyz="0"
               izz="0.01" />
    </inertial> 
<visual>
  <origin xyz="0 0 ${-leg_height}" rpy="0 0 0" />
  <geometry>
        <box size="${leg_width} ${leg_width} ${leg_height}"/>
  </geometry>
  <material name="brown_transparent"/>
</visual>
<collision>
  <origin xyz="0 0 ${-leg_height}" rpy="0 0 0" />
  <geometry>
        <box size="${leg_width} ${leg_width} ${leg_height}"/>
  </geometry>
  <material name="brown_transparent"/>
</collision>
</link>

<!-- Base to third Leg-->
<joint name="base_to_third_leg" type="fixed">
  <parent link="table_base"/>
  <child link="third_leg"/>
  <axis xyz="0 0 1"/>
  <origin rpy="0.0 0.0 0.0" xyz="-${table_base_width/2 - 0.03} ${table_base_length/2 - 0.03} ${leg_height*1.5}"/>
</joint>

<!--Fourth Leg -->
<link name = "fourth_leg">
<inertial>
      <mass value="1.0" />
      <origin xyz="0 0 ${-leg_height}" />
      <inertia ixx="0.1" ixy="0"  ixz="0"
               iyy="0.1" iyz="0"
               izz="0.01" />
    </inertial> 
<visual>
  <origin xyz="0 0 ${-leg_height}" rpy="0 0 0" />
  <geometry>
        <box size="${leg_width} ${leg_width} ${leg_height}"/>
  </geometry>
  <material name="brown_transparent"/>
</visual>
<collision>
  <origin xyz="0 0 ${-leg_height}" rpy="0 0 0" />
  <geometry>
        <box size="${leg_width} ${leg_width} ${leg_height}"/>
  </geometry>
  <material name="brown_transparent"/>
</collision>
</link>

<!-- Base to third Leg-->
<joint name="base_to_fourth_leg" type="fixed">
  <parent link="table_base"/>
  <child link="fourth_leg"/>
  <axis xyz="0 0 1"/>
  <origin rpy="0.0 0.0 0.0" xyz="${table_base_width/2 - 0.03} -${table_base_length/2 - 0.03} ${leg_height*1.5}"/>
</joint>





<gazebo reference="table_base">
   <material>Gazebo/Wood</material>
   <mu1>50.0</mu1>
   <mu2>50.0</mu2>
   <kp>1000000.0</kp>
   <kd>1.0</kd>
</gazebo>

<gazebo reference="first_leg">
   <material>Gazebo/Wood</material>
</gazebo>

<gazebo reference="second_leg">
   <material>Gazebo/Wood</material>
</gazebo>

<gazebo reference="third_leg">
   <material>Gazebo/Wood</material>
</gazebo>

<gazebo reference="fourth_leg">
   <material>Gazebo/Wood</material>
</gazebo>





</robot>


















































